name: CI

on:
  push:
    branches: ['*']  # Run on any branch
  pull_request:
    branches: ['*']  # Run on PRs to any branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Run tests with coverage
        run: |
          uv run pytest tests/ -v --cov=mcp_server_ds --cov-report=term-missing --cov-report=xml --cov-fail-under=75
